### ISSUE TITLE
Monitor with sonar cloud?

### ISSUE THREAD

**Issue by Leonardo-Ferreira** [casbin/Casbin.NET#220]
Sonarcloud is free for open source projects. Let's use it!

**Comment by hsluoyz** [comment]
@Leonardo-Ferreira hi, can you make a PR to integrate it?

**Comment by Leonardo-Ferreira** [comment]
@hsluoyz I could do the whole thing if you add me as member of the casbin org with rights to manage/add secrets... each repo would need its own build yml.

**Comment by hsluoyz** [comment]
@Leonardo-Ferreira invited, and I also added the secret:

![image](https://user-images.githubusercontent.com/3787410/141321523-bb854f88-c41c-44d9-bc5e-4c449b7b11a1.png)

But I'm not quite sure about how to add the yml file correctly. The following info is what I got from the Sonarcloud site. Can you help make it work (by making a PR)?

Create or update your .github/workflows/build.yml

Here is a base configuration to run a SonarCloud analysis on your master branch and Pull Requests. If you already have some GitHub Actions, you might want to just add some of these new steps to an existing one.

```
name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache SonarCloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v1
        with:
          path: .\.sonar\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner
      - name: Install SonarCloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -Path .\.sonar\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |
          .\.sonar\scanner\dotnet-sonarscanner begin /k:"casbin_Casbin.NET" /o:"casbin" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
          <insert_your_build_command>
          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
```

Replace <insert_your_build_command> by the actual one.
